### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by ericntd** [vlad-ignatov/react-numeric-input#1]
I'm using babelify 6.4.0 and browserify 12.0.1
```
[19:19:16] Browserify Error 
/Users/eric/af/frontend_app/node_modules/react-numeric-input/src/NumericInput.jsx:1
import { PropTypes, Component } from 'react';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by vlad-ignatov** [comment]
This should be a matter of build configuration. It is a parse error which means that the expression is not recognised (modules not supported). Did you include the necessary presets for es6 and react?

Maybe this can help you: https://github.com/babel/babelify/issues/103

**Comment by vlad-ignatov** [comment]
Any development on this one?

**Comment by ericntd** [comment]
I realised that your library depends on React 0.14 while I'm still using 0.13 so I've decided to go with another solution, thank you
