### ISSUE TITLE
Minor clarification in README for usage

### ISSUE THREAD

**Issue by pk1m** [vlad-ignatov/react-numeric-input#10]
Slight clarification between installation/usage. 

Installation and Usage is slightly misleading
`var NumericInput = require('react-numeric-input');` 
`<NumericInput />` 

In reality you have to access the NumericInput within the import.
`var NumericInput = require('react-numeric-input').NumericInput;`

**Comment by vlad-ignatov** [comment]
Thank you for reporting this. It was fixed in the latest release - 2.0.4
