### ISSUE TITLE
_valueAsNumber can't be found

### ISSUE THREAD

**Issue by justin-hackin** [vlad-ignatov/react-numeric-input#11]
In the documentation, demo, and tests I could not find any reference to how to extract the numeric value of the input through the use of the apparent _valueAsNumber 

```
<NumericInput ref="myNumericInput"/>

this.refs.myNumericInput._valueAsNumber
>>undefined
this.refs.myNumericInput.valueAsNumber
>>undefined
this.refs.myNumericInput.refs.input.valueAsNumber
>>NaN
this.refs.myNumericInput.refs.input._valueAsNumber
>>undefined
this.refs.myNumericInput.refs.input.value
>>"5.00"
```

Can you please indicate how to use the _valueAsNumber  property ?

**Comment by vlad-ignatov** [comment]
That is correct. The documentation for that is outdated and I will fix it ASAP. That property is now replaced with `getValueAsNumber()` function. Something like this should work:
```js
this.refs.myNumericInput.refs.input.getValueAsNumber()
```
