### ISSUE TITLE
react 15.2.1 gives error, Warning: Unknown props `mobile`, `onSelectStart` on <input> tag

### ISSUE THREAD

**Issue by cfkenandy** [vlad-ignatov/react-numeric-input#16]
### Problem description
I'm using "react": "^15.2.1", and "react-numeric-input": "^2.0.4".  When I use this component, it gives me the following error,

warning.js:44 Warning: Unknown props `mobile`, `onSelectStart` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in input (created by NumericInput)
    in span (created by NumericInput)
    in NumericInput (created by kNumericInput)
    in div (created by KNumericInput)
    in div (created by KNumericInput)
    in KNumericInput (created by KComponentWrapper)
    in div (created by KComponentWrapper)
    in KComponentWrapper (created by KForm)
    in div (created by Paper)
    in Paper (created by KForm)
    in KForm (created by PageDetails)
    in div (created by CardText)
    in CardText (created by PageDetails)
    in div (created by Card)
    in div (created by Paper)
    in Paper (created by Card)
    in Card (created by PageDetails)
    in PageDetails (created by KObjectPage)
    in div (created by Paper)
    in Paper (created by KObjectPage)
    in KObjectPage (created by Connect(KObjectPage))
    in Connect(KObjectPage) (created by RouterContext)
    in div (created by Main)
    in div (created by Main)
    in MuiThemeProvider (created by Main)
    in Main (created by Connect(Main))
    in Connect(Main) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider

### Steps to reproduce
1. npm install react and react-numeric-input
2. Initialize the component.

                   import NumericInput from 'react-numeric-input'
                    <NumericInput
                        className="numericInput"
                        min={fieldContext.minValue}
                        max={fieldContext.maxValue}
                        value={this.props.value}
                        onChange={this.handleChange.bind(this)}
                        onBlur={this.handleBlur.bind(this)}
                        onFocus={this.handleFocus.bind(this)}
                        style={KNumericInputStyle}
                    />
Possible solution: https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b

**Comment by fetis** [comment]
I have this issue too.

**Comment by vlad-ignatov** [comment]
The latest version (2.0.5) is compatible with React 15.2 and 15.3
