### ISSUE TITLE
Cannot type in number when `min` prop is set

### ISSUE THREAD

**Issue by MrMentor** [vlad-ignatov/react-numeric-input#19]
When you try to use this component with the `min` property set - then you can't type numbers in a normal way.
Ex. you have `min=100` - now try to type in 200 into input - it's impossible in normal way. You need to first add 2 at the start and then remove 1.
The way i see it - `n = Math.min( Math.max(n, this.props.min), this.props.max );` should be disabled when input is focused. And parsing should occur on blur.

There is also a bug when using `min` property with `onChange` event. When you have for ex. `min=100` and type 1 into input - it gets changed to `100` but `onChange` is fired only for typing 1, not on changing to 100.

Same thing according to formatted numbers. When you type in one character, cursor goes to the end of the string, disallowing you to type whole number in one go. I needed to hack it - disable formatting on `focus` - and re-enabling it on `blur`.

**Comment by vlad-ignatov** [comment]
Thank you for reporting. All of those issues should be fixed in v2.0.5.
