### ISSUE TITLE
Hours and minutes

### ISSUE THREAD

**Issue by isuvorov** [vlad-ignatov/react-numeric-input#22]
How can I do  60nth minutes  format with : delimiter?

```
13:15
12:30
14:45
```

**Comment by vlad-ignatov** [comment]
Sure you can. To use it as such a time picker you will have to do several things:

1. Use the input to represent the time as number with `value={Date.now()}`
2. Set the step to one minute with `step={1000*60}`
3. Use custom format function. If you are using library like moment the function might look like this:
```js
format={n => moment(n).format('HH:mm')}
```
or with native JS:
```js
format={n => {
    let date = new Date(n)
    let hour = date.getHours()
    let minutes = date.getMinutes()

    return [
        hours < 10 ? "0" + hours : hours,
        minutes < 10 ? "0" + minutes : minutes
    ].join(":")
}}
```

4. And finally you will need a custom parse function that knows how to convert that time back to timestamp number. Assuming that you are only interested in the time portion it might look like this:
```js
parse={str => {
    let date = new Date()
    let tokens = str.trim().split(":")
    date.setHours(+(tokens[0] || 0))
    date.setHours(+(tokens[1] || 0))
    return date.getTime();
}}
```

I haven't tested that but unless I've typed something wrong it should work or at least should illustrate the basic idea.
