### ISSUE TITLE
Strange bug with backspace and up/down arrow keys

### ISSUE THREAD

**Issue by isuvorov** [vlad-ignatov/react-numeric-input#23]
1. Click in NumericInput 
2. Click in textarea
3. When textarea  changed -> setState({comment:e.target.value}) -> rerender form with textarea & NumericInput

If you typing chars - all good, but when type backspace, arrow up, arrow down textarea unfocused and changing NumericInput

Video: https://www.youtube.com/watch?v=kxUnupPc2GQ

**Comment by Omnomios** [comment]
I'm having the same problem with this component and a textarea on the same page. It seems like the numeric input is half stealing focus on update.

Can you add a prop that disables all keyboard interaction and another prop that disables all focus control within the component?

**Comment by vlad-ignatov** [comment]
Should be fixed since 2.0.9.
