### ISSUE TITLE
Numeric keyboard on mobile

### ISSUE THREAD

**Issue by samuelsimoes** [vlad-ignatov/react-numeric-input#24]
Hi, there's any way to make the plugin behaves a little bit more like the `type=number` on mobile opening the numeric keyboard by default? When you start to edit a `type=number` field on mobile the numeric keyboard opens by default and it helps a lot on the form usability.

Thanks for your attention.

**Comment by dcousens** [comment]
@vlad-ignatov is it simply not compatible?

**Comment by onemanstartup** [comment]
https://developer.mozilla.org/en/docs/Web/HTML/Element/input inputmode="numeric" This should work

**Comment by vlad-ignatov** [comment]
You should be able to make that using combination of `pattern` and `inputmode` props. For example `pattern="[0-9]*" inputmode="numeric"` - https://stackoverflow.com/questions/6178556/phone-numeric-keyboard-for-text-input.

This component supports more than just numbers thus it relies on `input[type="text"]` but at least you are able to invoke the numeric keyboard if you only work with integers.
