### ISSUE TITLE
broken in safari since 2.0.5

### ISSUE THREAD

**Issue by jeacott1** [vlad-ignatov/react-numeric-input#26]
Hi there,
 nice component, but having a problem with safari.
  v2.0.4 worked fine with safari, but since then, it prevents switching focus properly, but worse,
 it eats all your ram and then explodes :)

![image](https://cloud.githubusercontent.com/assets/16600100/21130083/f1923ff6-c155-11e6-8535-e4823d2a94c2.png)

to reproduce, visit your demo link on a mac with safari, and click the up arrow on the first 2 input fields.
http://vlad-ignatov.github.io/react-numeric-input/examples/v2.0.5/index.html

**Comment by Emnalyeriar** [comment]
I second this. Downgrading to 2.0.4 resolved this issue.

**Comment by Terminux** [comment]
Hi.

The problem comes from the restoration of `selectionStart` and` selectionEnd` which generates a focus on each update. The PR #25 made by @Saniol  fix this issue

**Comment by vlad-ignatov** [comment]
Fixed in 2.0.7
