### ISSUE TITLE
Doesn't work on Chrome

### ISSUE THREAD

**Issue by edouardbrasier** [vlad-ignatov/react-numeric-input#29]
Hello,

I am not an expert but in Chrome it seems that it doesn't work on Chrome.
On my computer it shows  + and - signs on the left and right of the input box instead of the spin up and down.
Anyone is having the same issue?
works fine with Edge and firefox.

Thanks

**Comment by nichesoftgh01** [comment]
Hi

**Comment by nichesoftgh01** [comment]
Make mobile attribute false in the component

**Comment by vlad-ignatov** [comment]
Indeed. If the demo (http://vlad-ignatov.github.io/react-numeric-input/examples/v2.0.5/index.html) works for you in Chrome but your own page does not, then it probably means that in your page `'ontouchstart' in document` evaluates to true. I guess that this might happen depending on what other scripts and libraries you have included. In such case you will have to always specify the `mobile` prop. It can be true, false, "auto" (which doesn't work for you) or a function that returns boolean.

**Comment by edouardbrasier** [comment]
Thanks for the reply.
To follow up
I have just looked at http://vlad-ignatov.github.io/react-numeric-input/examples/v2.0.5/index.html  with chrome and I have the same issue
+ and - are in the right and left instead of being a spin box with up and down arrow
I will reopen and issue with screenshot
