### ISSUE TITLE
Problem when importing

### ISSUE THREAD

**Issue by lukaszgrolik** [vlad-ignatov/react-numeric-input#3]
```js
import NumericInput from 'react-numeric-input';
```

```
[...]\node_modules\react-numeric-input\src\NumericInput.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import { PropTypes, Component } from 'react';
|
| const KEYCODE_UP   = 38;
```

I'm using webpack 1.12.11 with babel 6.4.0 and react 0.14.6. In my app ES6 imports work correctly so all necessary presets are included - just this module doesn't work. It's probably connected with #1

**Comment by vlad-ignatov** [comment]
Sorry for not being able to respond very quickly. The problem is rather complex and instead of trying to fix it I intend to release v2 in the next 1-2 days. It does support all the latest dependencies and has some new features. I will let you know when it's available.

**Comment by vlad-ignatov** [comment]
Here you go. The latest release is 2.0.1. You can just run `npm update react-numeric-input --save` and it should work.
