### ISSUE TITLE
Max value not respected when entering by keyboard

### ISSUE THREAD

**Issue by stahlmanDesign** [vlad-ignatov/react-numeric-input#32]
When I use the buttons to select a number, the min and max values are respected.

When I type a number however, I can type anything and the input value is only limited when I tab away (the actual value is respected, just not the display)

Is it possible to immediately enforce the max number when typing?

**Comment by vlad-ignatov** [comment]
Unfortunately, I have to say it is not possible if we want to keep the input's behaviour as natural as possible. To achieve that, the function that parses the value will have to convert it to number, apply min/max and precision and that makes it impossible to type in many cases (people may have to select a single digit out of the whole number and then hit a key to edit it. That is just the tip of the iceberg - there are also things like `.`, `-`, `+`, custom formats...

That is why the input is in "loose mode" while you are typing and switches back to "strict" on blur (plus that is still better than what you get from the native `input[type="number"` in Chrome).

**Comment by vlad-ignatov** [comment]
Actually, since 2.2.0 I have added the `strict` boolean prop which defaults to false. In strict mode the input will be corrected while you type and in loose mode you can type anything and it will be formatted on blur. Hope that helps.
