### ISSUE TITLE
Backspacing over value in a field with precision > 0 adds extra zeros

### ISSUE THREAD

**Issue by rpilic** [vlad-ignatov/react-numeric-input#33]
On the demos page, set the cursor to the end of the text in the field and have the precision set to a value greater than 0. Then start backspacing - once you get to the character immediately to the left of the decimal point, it adds the same number of zeros to the value as the precision.

Ex:
Precision = 2
Value = 50.00
Backspacing will change the value to 5000.0.

**Comment by Terminux** [comment]
Hi @vlad-ignatov !

I have made a pull request to fix this issue.

**Comment by vlad-ignatov** [comment]
This was fixed in 2.0.9 and again in 2.1.0. @Terminux, you may want to update your fork because even though your PR fixed this issue, it was preventing the input from being editable if you select all first. In 2.1.0 includes different fix for the backspace issue.
