### ISSUE TITLE
"Snap" value to next step.

### ISSUE THREAD

**Issue by erikmoren** [vlad-ignatov/react-numeric-input#35]
Hi, thanks for a great component :-) 

I have a question: Is it possible to make the value "snap" to the next step when stepping up/down?

For example: I have a input with step: 0.25, precision: 2 and a value of 1.18.
Pressing the up button makes the value of course go to 1.43. Just wondering if it is possible for the value to "snap" to 1.25 instead..?

Sincerely,
Erik

**Comment by vlad-ignatov** [comment]
There is a "snap" boolean prop for that since 2.1.0. I hope this works for you.
