### ISSUE TITLE
IE10 Type Error

### ISSUE THREAD

**Issue by archernc** [vlad-ignatov/react-numeric-input#37]
Was curious to know if IE10 was meant to be supported? Validated using the demo site that an error gets thrown on line 153 with error "Invalid operand to 'in': Object expected"

![capture](https://cloud.githubusercontent.com/assets/11719139/23854158/816f62d2-07c6-11e7-8bc6-64c9f6740025.PNG)

**Comment by archernc** [comment]
Resolved our current issues by rolling back to v2.0.4 but still curious.  Thanks.

**Comment by karamanolev** [comment]
@vlad-ignatov I'm observing the exact same error in the exact sample place. Nothing fancy. IE9 in our case. Can you fix it?

**Comment by karamanolev** [comment]
More info: the error is actually caused by this https://github.com/babel/babelify/issues/133 . Not exactly sure if this library can fix it in any way. There are some workarounds, but none worked for me.

**Comment by karamanolev** [comment]
It seems that building this with the latest Babel fixes it, so what I did was copy NumericInput.jsx over to our project so that it gets built by our Webpack. Otherwise it's using the pre-built index.js, which is probably built with an older Babel/Webpack and therefore has this issue.
