### ISSUE TITLE
Why not use <input type="number">

### ISSUE THREAD

**Issue by hongyuan1306** [vlad-ignatov/react-numeric-input#40]
The component uses `<input type="text" >` as the underlying input control. While this works fine on the desktop, on a phone, normally I would like the numeric keypad to appear whenever the control has focus.

Having `<input type="text">` makes it very annoying to enter a number using this component as one has to switch input method first.

So the question is, why not use `<input type="number">` as the underlying input control? And whether I can override the default input type?

**Comment by cdtinney** [comment]
The mobile use case is essentially the only benefit, as far as I can tell.

You'd have to override different browser behavior w.r.t rendering number inputs, e.g. up and down buttons in WebKit, as well as validation.

**Comment by vlad-ignatov** [comment]
Thanks @cdtinney, that is correct! I would add that this component provides more functionality (like custom formats) which is not possible with the native number inputs. As for the input method see  #24 .
