### ISSUE TITLE
NumericInput value is reset.

### ISSUE THREAD

**Issue by prettyGoo** [vlad-ignatov/react-numeric-input#41]
I send requests every 1s in my parent component. Then I noticed that somehow the value of NumericInput in child component is reset every 1s as well . Other inputs (from react-bootstrap) are not affected by request and not reset. Any idea how to fix it?

**Comment by vlad-ignatov** [comment]
That is odd. Can you provide a link?

**Comment by vlad-ignatov** [comment]
There was a bug in earlier versions that could result in changing the value if the parent component re-renders and does not provide a value for the NumericInput. This is fixed now and might help you if that was the reason.

**Comment by vlad-ignatov** [comment]
I am closing this because it is too old and should be fixed already.
