### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by rodri042** [vlad-ignatov/react-numeric-input#42]
It started to throw that warning after installing the library

**Comment by dcefram** [comment]
This is because 2.0.8 isn't yet published to npm :(

but there's already a comment mentioning the maintainer to publish it to npm (https://github.com/vlad-ignatov/react-numeric-input/pull/43#issuecomment-299581993)

**Comment by vijayst** [comment]
I have the same issue. I will appreciate if this gets published. Thanks.

**Comment by ls-guillaume-lambert** [comment]
Yes please! @vlad-ignatov is it possible to publish this merged commit? Thanks!

**Comment by shahyar** [comment]
I've forked this, and though it isn't on NPM, you can set your `package.json` for `2.0.8` with
`"react-numeric-input": "https://github.com/shahyar/react-numeric-input.git#b01f1f9"`

Alternatively, `2.0.9` also resolves #50 with
`"react-numeric-input": "https://github.com/shahyar/react-numeric-input.git#5868a02"`

Hopefully the maintainer will return.

**Comment by vlad-ignatov** [comment]
Sorry guys. I recently moved with my family to another country and didn't have time for this but things are coming back to normal. All the pull requests are merged and the latest version is released as 2.0.9. I am now trying to address the remaining issues.

**Comment by ls-guillaume-lambert** [comment]
No problem at all, thanks for taking the time to reply!
