### ISSUE TITLE
"onTouchStart" preventDefault is ignored, causes double step to happen

### ISSUE THREAD

**Issue by dudevon** [vlad-ignatov/react-numeric-input#44]
This was tested on Chrome 58 with responsive mode switched on which means it treats clicks as touch events. This results in step being done twice on a single click.

![step bug on touch](http://i.imgur.com/duFvLQD.gif)

The following message gets logged in the console.

```[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080```

**Comment by omarzion** [comment]
Same issue here

**Comment by lanceon** [comment]
Reproduced in react-numeric-input v2.0.9 and 2.1.0 in desktop Chrome in device mode and latest Chrome browser on Android.

**Comment by lanceon** [comment]
Hi @vlad-ignatov,

Made a quick fix on this issue according to recommendation on developers.google.com:
https://developers.google.com/web/updates/2017/01/scrolling-intervention

```
If your touchstart listener calls preventDefault(), ensure preventDefault() is also called from associated touchend listeners to continue suppressing the generation of click events and other default tap behavior.
```

Please review and merge if appropriate:
https://github.com/vlad-ignatov/react-numeric-input/pull/56
That fixes the double click issue in devtools' device mode so should work on mobiles with touch events.

**Comment by vlad-ignatov** [comment]
This is now fixed thanks to @lanceon.
