### ISSUE TITLE
Inserting field with value out of range

### ISSUE THREAD

**Issue by saintego** [vlad-ignatov/react-numeric-input#45]
I use it with redux-form. I have value out of the min-max range. Input field shows correctly minimal value instead of original one. When I click in the input field I have original value instead of minimal, what I think is not correct. After leaving field onChange is called and value is correctly set to minimal value. 
Maybe to call onChange in _toNumber function, when n is changed because of range would help.

**Comment by vlad-ignatov** [comment]
Does that still happen with the latest version?

**Comment by vlad-ignatov** [comment]
This will not happen in the latest version in strict mode (`strict` prop equal true). In loose mode the initial value can be invalid but will be formatted on the first blur event.
