### ISSUE TITLE
No Ability to AutoFocus

### ISSUE THREAD

**Issue by axelak** [vlad-ignatov/react-numeric-input#47]
There should be an ability to pass in an autoFocus prop that can be used to set the inputFocus state variable.

**Comment by cdtinney** [comment]
In the docs, it states:

>Any other option is passed directly the input created by the component.

There is an `onFocus` handler attached to the input that does set the `inputFocus` state to `true`. 

If you set `autoFocus` to true, does this not occur?

**Comment by vlad-ignatov** [comment]
Yes, you can simply add `autoFocus` to your props.
