### ISSUE TITLE
does not work with typescript

### ISSUE THREAD

**Issue by chad-lp** [vlad-ignatov/react-numeric-input#49]
When trying to invoke from typescript file, I get the following runtime error:

```warning.js:36 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `xyz`.```

where `xyz` is the name of the file I'm calling from.
Everything compiles fine but react component does not render.

removing the `NumberInput` causes component to render

**Comment by vlad-ignatov** [comment]
Could you provide an example of how you are importing it? Perhaps you need to do `import * as NumericInput from "react-numeric-input"`?
