### ISSUE TITLE
onChange callback/rethink state model?

### ISSUE THREAD

**Issue by dandelany** [vlad-ignatov/react-numeric-input#5]
I like the UI work you've done, especially the arrow keys, but I'm not sure I understand how this component is useful if it A) stores its own state and B) doesn't have an onChange prop that gets called when the input changes? How is the value of this input supposed to affect the rest of the app state? The only way I can see is to use the `parse` prop but that feels like a hack.

IMHO a successful numeric input probably looks more like [React widgets' approach](http://jquense.github.io/react-widgets/docs/#/numberpicker), minus all of the [localization complexity](http://jquense.github.io/react-widgets/docs/#/i18n) they've introduced. It's stateless & controlled by `props.value` always, not just at initialization. The parent component is then expected to use the provided onChange callback to do what it needs to in order to update app state, which is then reflected in a props update to NumberInput. State should be stored further up the hierarchy, not at a 'leaf' node like an `<input>`.

**Comment by vlad-ignatov** [comment]
Thank you for your comments. Those are some valid points which I will have to consider. Strictly speaking, this component cannot be stateless. It does have some specific stuff that represent it's own state and that shouldn't concern you, but right now I see why it does. You are correct that one should be able to pass props after initialization and "modify" the component. It was designed as simple form element, i.e. place it in a form and submit... However, you have identified a limitation that prevents if from being  part of other scenarios specific to the React component structures. The parent component should be able to set the value (but of course the component should be usable by it's own too, without depending on any parents).

There will be a new version for that. The component will still have some state but it should appear as
stateless to the outside world. The "onChange" (and other props) will be allowed. This is possible and I have a demo already but I'm not sure if I can release it this week. 

Finally, just to clarify, here is what I'm currently testing with. It's has one "parent component" that contains two numeric inputs and stores a "length" property in it's state. One of the inputs is for length in inches and another for length in centimetres. When you change one of them, the other one gets updated via the parents state so they are always in sync... Does that look like something that covers your requirements?
```js
import React        from "react"
import NumericInput from "react-numeric-input"

export default class LengthWidget extends React.Component
{
    constructor(...args) {
        super(...args)
        this.state = {
            length: 0 // in millimeters
        }
        this.setLengthInInches = this.setLengthInInches.bind(this)
        this.setLengthInCentimeters = this.setLengthInCentimeters.bind(this)
    }
    
    setLengthInInches(n) {
        this.setState({ length: n / 0.0393701 })
    }

    setLengthInCentimeters(n) {
        this.setState({ length: n * 10 })
    }
    
    format_cm(value) {
        return value + "cm"
    }
    
    format_in(value) {
        return value + "in"
    }
    
    render() {
        return (
            <div>
                <p className="text-muted">
                    Internal value: {
                        (Math.round( this.state.length * 100 ) / 100).toFixed(2)
                    }mm
                </p>
                <label>cm: </label>
                <NumericInput
                    className="form-control"
                    value={ this.state.length / 10 }
                    onChange={ this.setLengthInCentimeters }
                    format={ this.format_cm }
                    precision={ 2 }
                    step={ 0.01 }
                />
                <br/>
                <label>in: </label>
                <NumericInput
                    className="form-control"
                    value={ this.state.length * 0.0393701 }
                    onChange={ this.setLengthInInches }
                    format={ this.format_in }
                    precision={ 2 }
                    step={ 0.01 }
                />
            </div>
        )
    }
}
```

**Comment by dandelany** [comment]
Yes, that example is exactly what I mean. :+1: 

[I ended up writing my own minimal version of this and added some notes](https://github.com/dandelany/vector-toy/blob/master/src/components/NumberInput.jsx). Feel free to use any of it that you find useful. It has state, to store the input string value, but "appears stateless from the outside" as you said. It also has an additional callback, `onValidChange` which is only called if the value is changed to a valid number - this is the callback that I actually use to set the parent's state, ensuring I don't get a `NaN` if the user types letters or something.

**Comment by 2easy** [comment]
+1 for the feature, the component cannot be now used with Redux, and this eliminates it for my case. Would be great to be able to pass onChange as a prop.

**Comment by vlad-ignatov** [comment]
Sorry guys. In fact, this has been ready for a while. I just don't have the time to make the official release but the code is on github. There are many new features and tests and it seems to work fine. If you need it right now you can do `npm install https://github.com/vlad-ignatov/react-numeric-input.git`. This will give you the latest version 2.0.2. I am making new interactive demo for it which is currently at the bottom of this page - http://vlad-ignatov.github.io/react-numeric-input/examples/v2.0.2/index.html.

I just need to finish that demo and update the readme before making the official release but I'm under 
a lot of pressure in my full-time job and can't spare any time right now. I hope I can do that over the weekend though.

**Comment by vlad-ignatov** [comment]
It is now official! NPM will install v2.0.3 by default.
@dandelany Thank you for the onValidChange idea. In my case onChange is only called after successful (valid) change of the internal numeric value but I also tried to make use of the built-in HTML5 input validation when available. Now I also have `onInvalid` and `onValid` as callback props.

**Comment by dandelany** [comment]
Great, glad it was helpful! I will check out the new release when I get a chance. Thanks!
