### ISSUE TITLE
Provide `parse` with input data

### ISSUE THREAD

**Issue by briandipalma** [vlad-ignatov/react-numeric-input#53]
When debugging I noticed there is a parsed numeric value stored in the input state, would it be possible to pass such data in to the `parse` callback?

**Comment by vlad-ignatov** [comment]
Yes, it is possible but I wonder if you could share why you would need it. My concern is that `state.value` is the **current** numeric value while the argument passed to parse is the string input value that is **about to be applied** (after `parse` converts it to number). In other words, the parse function signature that you are proposing might be `parse(newStringValue, oldNumberValue)`. That is OK but I'm afraid that people may get confused and incorrectly tempted to use and return that second argument which would lock the component as if it is read-only...

I just cannot imagine good use case for it but that does not mean there isn't one so I hope to hear more about it.

**Comment by briandipalma** [comment]
You're absolutely correct, I didn't realise that value was the current value.
