### ISSUE TITLE
Focus programatically

### ISSUE THREAD

**Issue by abeikverdi** [vlad-ignatov/react-numeric-input#58]
I know there is onFocus props in there. I wanna know how I can focus into the content from somewhere else. I assigned a ref to it but it didnt work and told me there is no focus function.

Is there anyway to achieve this?

**Comment by vlad-ignatov** [comment]
If you have set a `ref` it will point to the component itself and not to the input element inside it.
This means that you should add `.refs.input` to your lookup chain. For example, if your ref is called "numericInput" you should do something like `...refs.numericInput.refs.input.focus()`.

You can also do this using regular DOM operations like:
```
document.querySelector("wherever .react-numeric-input input").focus()
```

**Comment by abeikverdi** [comment]
Thanks. That works
