### ISSUE TITLE
Type annotations for TypeScript is missing?

### ISSUE THREAD

**Issue by fjallemark** [vlad-ignatov/react-numeric-input#59]
Documentation states how to import the component in TypeScript, implicating that NumericInput should work also with TypeScript. However, Visual Code complains about a missing type declaration 
Niether of these commands installs the required typedeclaration file:

- npm install react-numeric-input --save
- npm install (at)types/react-numeric-input returns 404

If intended to be used with TypeScript, please also provide a type definition.

**Comment by heatherbooker** [comment]
I added them to Definitely Typed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21151/commits/a9d3cb8830c94e041ddfda47cd953b657a3df88f ;  you should soon (after deploy, idk how often that happens) be able to `npm install @types/react-numeric-input`. Feel free to improve upon them by PRing to that lib!
