### ISSUE TITLE
Getting an unknown prop warning using "strict" mode

### ISSUE THREAD

**Issue by gregdillon** [vlad-ignatov/react-numeric-input#60]
I noticed in the latest version you have added a "strict" mode prop. When attempting to set this I am getting this error...

Warning: Unknown prop `strict` on <input> tag. Remove this prop from the element ...

It also does not seem to be functioning as expected.

**Comment by vlad-ignatov** [comment]
I am sorry to hear that you are having problems with this. However, that should not happen.  Looking at the cade, I can tell that the `strict` prop cannot reach the input. Also, it does not happen on the demo (the "Interactive Demo" section at the bottom of http://vlad-ignatov.github.io/react-numeric-input/).

Please make sure that you are using the latest version 2.2.0 and re-install if needed.

**Comment by vlad-ignatov** [comment]
Closing this because it is too old and should not happen any more
