### ISSUE TITLE
style={false} produces eslint warning

### ISSUE THREAD

**Issue by intrueder** [vlad-ignatov/react-numeric-input#68]
The warning is `Enforce style prop value being an object (react/style-prop-object)`
Is it possible to make the component be able to work with `style={null}` to disable inline styles?
It's not a big deal to disable warning, but `style={false}` is a bit confusing

**Comment by vlad-ignatov** [comment]
`style={null}` or `style={{}}` means "I don't have any custom styles that I want to apply" and `style={false}` means "please don't apply any styles".  However, eslint is great tool that I respect and that is why `style={false}` is deprecated (still works). You can now use the new `noStyle` boolean prop for that.
