### ISSUE TITLE
StringValue reappears in input when mouse hovers over the up/down button after clicking away

### ISSUE THREAD

**Issue by mjosh954** [vlad-ignatov/react-numeric-input#69]
Encountered a bug where when a user types in anything in the numeric box (incl special characters: $#@as), then click away from the box, the value gets validated and cleaned up. But when the mouse hovers over the up/down button, the string value reappears until you click inside the numeric textbox.

**Comment by JiniHendrix** [comment]
im getting the same issue

**Comment by wuyingyou** [comment]
+1

**Comment by vlad-ignatov** [comment]
This is fixed in the latest release.
