### ISSUE TITLE
Add prop (or overload style prop) for disabling inline styling

### ISSUE THREAD

**Issue by acusti** [vlad-ignatov/react-numeric-input#7]
It would be great to be able to override the inline styling with a `disableStyles` prop or by allowing the `style` prop to be an object or boolean false. We are using the component, and our team does styling from separate `less` files, which meant throwing `!important` on everything.

Happy to make a PR for it for either implementation!

**Comment by vlad-ignatov** [comment]
Thanks, that is a great idea. Until I manage to find some time for that, I'd suggest trying to override the default styles (they are in static property for that reason). You should be able to modify them or just empty everything (but keep the keys). I haven't tried it, but something like this should work:

```js
var NumericInput = require("react-numeric-input")
NumericInput.style = {
        wrap: {},
        'wrap.hasFormControl': {},
        arrowUp: {},
        arrowDown: {},
        plus: {},
        minus: {},
        btn: {},
        btnUp: {},
        'btnUp.mobile': {},
        btnDown: {},
        'btnDown.mobile': {},
        'btn:hover': {},
        'btn:active': {}
        'btn:disabled': {}
        input: {},
        'input:not(.form-control)': {},
        'input.mobile': {},
        'input:focus': {},
        'input:disabled': {}
    };

// Now use it as usual...
```

**Comment by acusti** [comment]
That worked great, thanks! Just missing a couple commas in your example.

```js
        'btn:active': {},
        'btn:disabled': {},
```

It also seemed to work to just set the style object as a completely empty object, i.e.:

```js
NumericInput.style = {};
```

I guess all of the `Object.assign` calls wind up passing around `undefined` and it just works.

**Comment by vlad-ignatov** [comment]
This is now added to the latest release (2.0.4). You can use `style={ false }` to disable the inline styles.
