### ISSUE TITLE
Can enter non-numeric characters

### ISSUE THREAD

**Issue by darrenklein** [vlad-ignatov/react-numeric-input#70]
First of all, thank you so much for writing this helpful component!

I find that I can type non-numeric characters in the input field... letters, special characters, etc... it would be great if there was an option to disable non-numeric characters.

Thanks!

**Comment by worthlutz** [comment]
+1

**Comment by AmilaDestro** [comment]
+1
By other parameters the component is very useful. Thank you for your work!

**Comment by apuntovanini** [comment]
+1, would you accept a PR that fixes this?

**Comment by darrenklein** [comment]
@apuntovanini I was totally about to ask that, too. To handle this in my app, I added

    onInput={restrictNumericInput}

to the NumericInput component, referring to this function:

	restrictNumericInput = (event) => {
		event.target.value = event.target.value.replace(/[^0-9]/g, "")
	}

If that's an adequate fix, seems like it'd be easy enough to integrate this (or something like it) as an option in this otherwise solid library.

**Comment by vlad-ignatov** [comment]
Hi and sorry for the delayed answer. In fact, there is an option for that. It is a boolean prop called `strict` which is false by default. I just realized that it is not documented so I will include it's description in the next release. Hope that helps.
