### ISSUE TITLE
React 16 compatibility

### ISSUE THREAD

**Issue by ekohl** [vlad-ignatov/react-numeric-input#71]
Now that React 16 is out it'd nice if the peerDependency allowed this. I think 15 and 16 are compatible but haven't tried it yet.

**Comment by 2manyvcos** [comment]
There is a weird issue when linking react-numeric-input to a project.

An error occurs when the component's state changes which indicates that there are versions of react 15 and 16 colliding.
<details>
<summary>Error screenshot</summary>

![image](https://user-images.githubusercontent.com/4709780/35613008-f2fd1126-066a-11e8-820d-82e73c652ea1.png)

</details>

This seems to be related to the devDependencies react and react-dom. Please see the following console output screenshots:

In react-numeric-input:
![image](https://user-images.githubusercontent.com/4709780/35613401-427fd84a-066c-11e8-9cfa-970717f862c1.png)

and in my demo project (with `npm link react-numeric-input`):
![image](https://user-images.githubusercontent.com/4709780/35613454-668c22fc-066c-11e8-944e-fce061453990.png)

When I use yarn in my demo project I even get following:
![image](https://user-images.githubusercontent.com/4709780/35613651-04e37022-066d-11e8-8bcd-0de7a776398a.png)

So it seems that the devDependencies version (^15.6.1) collides with my demo project's one (^16).

It only works after doing
```shell
npm remove --save --dev react react-dom
npm run build
```
in my local version of react-numeric-input.

So should we remove react and react-dom from the devDependencies or would this be a problem?
