### ISSUE TITLE
Hi there,

### ISSUE THREAD

**Issue by wuyingyou** [vlad-ignatov/react-numeric-input#74]
This component is amazing and I wanna introduce it into my project. But, after I review your code, I found some issues. Let's improve it.

1. Anti React best practice - mute the state directly. This way it still work, but if you derive from PureComponet then it does not work.

e.g.  **this.state.inputFocus = true**  -------> this.setState({inputFocus: true})

2. Sometimes, input some invalid characters into the numeric field, hove the component, it's shows the bad data. 

e.g. 
     a. Enter '123',
     b. Enter 'abc' after '123'  ----> '123abc', invalid input.
     c. Blur the component, hence the component shows 123, this is good.
     d. Focus the component, it show '123abc'. I thinks it's incorrect here.

Please try several times from step a to step d, you can get it.

Could you please help to correct it?

**Comment by wuyingyou** [comment]
@vlad-ignatov @shahyar @acusti @Terminux

**Comment by vlad-ignatov** [comment]
All these should have been fixed in the latest release.

**Comment by wuyingyou** [comment]
That's great, thanks man.
