### ISSUE TITLE
Synthetic event warning on React15.0.1

### ISSUE THREAD

**Issue by hafen** [vlad-ignatov/react-numeric-input#8]
When adding event handlers to numeric input components in React 15.0.1, I get the following warning in the javascript console:

> Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `type` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

**Comment by mandrichenko** [comment]
Same problem. React 15.0.1. 
Simple usage: 
<NumericInput min={0} max={100} value={50}/>

Generates warning.

**Comment by vlad-ignatov** [comment]
There is new release (2.0.4) and the component is now compatible with React 15.
