### ISSUE TITLE
Input does not work with ReactDOM 16.3.0

### ISSUE THREAD

**Issue by EmmaSimon** [vlad-ignatov/react-numeric-input#89]
If you're using react-dom ^16.3.0, it becomes impossible to change the value of the numeric input. Clicking the buttons and typing in the input both do nothing.

**Comment by EmmaSimon** [comment]
This seems to only be happening in an older version under very specific circumstances. I can't reproduce in the latest version.

I can reproduce something similar, but not quite the same, by calling `setState` in `onChange`.
https://codesandbox.io/s/qqpox37rkw
This may be what's happening in #63, but it's not what I was originally seeing, and happens in any version of react.

**Comment by davidesamp** [comment]
Sorry but I've the same issue also with the latest version. I've upgraded my React version to 16.3 and the value does not change yet. How did you solve it?
Consider that if I try something like this:

`<NumericInput
      onChange={(value) => console.log("Change value", value)}
       value={value} />`

Nothing happens when I try to change the input value.

**Comment by intositeme** [comment]
Did you manage to solve this? I'm getting this issue as well. In my page, i have multiple instances of the component. But just 1 some how is not working. In your code pen example, if you go to the NumInput.js and remove the `value` prop from NumericInput, it works and call the onChange handler. But then you can set the value from redux/state/prop
